//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hapiservice.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\'\',\'Pending - Install\',\'Pending - PD\',\'Pending - PS\',\'Pending - Upgrade\',\'File CR" +
            "\',\'Await SW Rel/Dev\',\'Pending ClientAction\',\'Awaiting Hosting Services\',\'File DB" +
            "A\'")]
        public string caseStatusNonWorkableGMBU {
            get {
                return ((string)(this["caseStatusNonWorkableGMBU"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\'\',\'Pending - Install\',\'Pending - PD\',\'Pending - PS\',\'Pending - Upgrade\',\'Solved " +
            "Pending Confirmation\',\'Suggested Resolution\',\'Awaiting Hosting Services\',\'File C" +
            "R\',\'Await SW Rel/Dev\',\'Pending ClientAction\'")]
        public string caseStatusNonWorkableECBU {
            get {
                return ((string)(this["caseStatusNonWorkableECBU"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ClarifyAuth {
            get {
                return ((bool)(this["ClarifyAuth"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\'Outgoing call\',\'Chat\',\'Incoming Call\'")]
        public string caseProactiveContact {
            get {
                return ((string)(this["caseProactiveContact"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\'Incoming Call\',\'Outgoing call\',\'Chat\',\'ACD - Live\'")]
        public string caseAllContact {
            get {
                return ((string)(this["caseAllContact"]));
            }
        }
    }
}
